### ISSUE TITLE
[feature request] Rails agnostic

### ISSUE THREAD

**Issue by goncalvesjoao** [RicardoBrazao/systematize#5]
I'd kiss you in the mouth if this could make my ruby gems manage their migrations without the need of **railties**.

Ok, I'd kiss you, don't know about the mouth thing :p

**Comment by goncalvesjoao** [comment]
Never mind I can live with that ^_^

**Comment by RicardoBrazao** [comment]
What a storm of emotions I had there... 😄 

PS. Can I still have that kiss? 😊
