### ISSUE TITLE
[feature request] rake systematize:create

### ISSUE THREAD

**Issue by goncalvesjoao** [RicardoBrazao/systematize#6]
So, I have a ruby gem that can run its migrations by itself thanks to this gem, but it can't create the database.

So we are missing the ```rake systematize:create```

I'll leave the contents of my Rakefile bellow so you can test and update your Readme.md as you please
```ruby
# Loading my gem
require File.expand_path('../config/boot', __FILE__)

require 'systematize' 

# Setting ActiveRecord database configuration
task :environment do
  ActiveRecord::Base.establish_connection ENV.fetch('DATABASE_URL')
end

# Loading systematize rake tasks
Rake.add_rakelib "#{Gem.loaded_specs['systematize'].full_gem_path}/lib/tasks" 

# Loading my gem tasks
Rake.add_rakelib File.expand_path('../tasks', __FILE__)
```

I'll investigate on how to implement the "create" task, but I'm guessing that you might have some insight  about that @RicardoBrazao.

**Comment by RicardoBrazao** [comment]
Interesting case indeed. I'll look into it 😄  !!

**Comment by RicardoBrazao** [comment]
@goncalvesjoao Just created [this PR](https://github.com/RicardoBrazao/systematize/pull/7) with some changes regarding the issue you raised.

**Comment by goncalvesjoao** [comment]
thank you

**Comment by goncalvesjoao** [comment]
Ok, turns out that it was unnecessary, because for your systematize:create to work I have to include in my Rakefile the ActiveRecord rake tasks and therefor ```rake db:create``` is naturally available.

I wanted to avoid having to load the ActiveRecord tasks and just load yours but I think there's no way to avoid it.

For those that have a ruby gem that doesn't depend on Rails, I'll leave this **Rakefile** that might help:
```ruby
# Loading your gem
require File.expand_path('../config/boot', __FILE__)

# Setting DatabaseTasks configuration, so that rake db:create might work
db_dir = File.expand_path('../db', __FILE__)

include ActiveRecord::Tasks

DatabaseTasks.env = ENV['ENV']
DatabaseTasks.db_dir = db_dir
DatabaseTasks.migrations_paths = File.join(db_dir, 'migrate')
DatabaseTasks.database_configuration = {
  ENV['ENV'] => ENV.fetch('DATABASE_URL')
}

# Setting ActiveRecord database configuration
task :environment do
  ActiveRecord::Base.establish_connection ENV.fetch('DATABASE_URL')
end

# Loading ActiveRecord database rake tasks
load 'active_record/railties/databases.rake'

# Loading systematize rake tasks
require 'systematize'

Rake.add_rakelib "#{Gem.loaded_specs['systematize'].full_gem_path}/lib/tasks"

# Loading your gem tasks
Rake.add_rakelib File.expand_path('../tasks', __FILE__)
```
